<?php

use Drupal\views_fieldsets\Plugin\views\field\Fieldset;

/**
 * Implements hook_theme().
 */
function views_fieldsets_theme() {
  $vars = ['fields' => [], 'classes' => ''];
  $path = drupal_get_path('module', 'views_fieldsets');

  $hooks['views_fieldsets_fieldset'] = [
    'variables' => $vars + ['legend' => '', 'collapsible' => TRUE, 'collapsed' => FALSE],
    'template' => 'views-fieldsets-fieldset',
    'path' => $path,
  ];

  $hooks['views_fieldsets_details'] = [
    'variables' => $vars + ['legend' => '', 'collapsed' => FALSE],
    'template' => 'views-fieldsets-details',
    'path' => $path,
  ];

  $hooks['views_fieldsets_div'] = [
    'variables' => $vars,
    'template' => 'views-fieldsets-div',
    'path' => $path,
  ];

  return $hooks;
}

/**
 * Implements hook_views_data().
 */
function views_fieldsets_views_data() {
  $data['views']['fieldset'] = array(
    'title' => t('Fieldset'),
    'help' => t('Create a group of fields.'),
    'field' => array(
      'id' => 'fieldset',
    ),
  );

  return $data;
}

/**
 * Implements hook_preprocess_views_view_fields().
 */
function views_fieldsets_preprocess_views_view_fields(&$vars) {
  $view = $vars['view'];

  Fieldset::replaceFieldsetHandlers($view, $vars['fields'], $vars['row']);
}
